---
title: "mastertable"
author: "Manunpat"
date: '2022-05-15'
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning=FALSE}
source(here::here("scripts/setup.R"))
```

```{r echo=FALSE, message=FALSE}
aisles <- read.csv(here::here("data/aisles.csv"), header = TRUE)
#missing value
sum(is.na(aisles)) #0

departments <- read.csv(here::here("data/departments.csv"), header = TRUE)
#missing value
sum(is.na(departments)) #0

products <- read.csv(here::here("data/products.csv"), header = TRUE)
#missing value
sum(is.na(products)) #0

order_products_train <- read.csv(here::here("data/order_products__train.csv"), header = TRUE)
#missing value
sum(is.na(order_products_train)) #0

orders <- read.csv(here::here("data/orders.csv"), header = TRUE)
#missing value
sum(is.na(orders)) #206209
max(orders$user_id) #206209
#meaning that data is complete

prior <- read.csv(here::here("data/order_products__prior.csv"), header = TRUE)

main <- orders %>%
  filter(eval_set == "train") %>%
  select(user_id, days_since_prior_order)

X1 <- orders %>%
  filter(eval_set == "prior") %>%
  group_by(user_id) %>%
  summarise(averageday_history = mean(days_since_prior_order, na.rm=TRUE))

X2 <- prior %>%
  left_join(orders, by = "order_id") %>%
  select(order_id, product_id, user_id, reordered) %>%
  left_join(products, by = "product_id") %>%
  select(-product_name, -aisle_id) %>%
  left_join(departments, by = "department_id") %>%
  group_by(user_id, department) %>%
  summarise(numorder = n()) %>%
  group_by(user_id) %>%
  mutate(numtotal = sum(numorder)) %>%
  mutate(percentorder = numorder/numtotal) %>%
  select(-numorder, -numtotal) %>%
  pivot_wider(names_from = "department", values_from = "percentorder")

X2[is.na(X2)] <- 0
  
main <- main %>%
  left_join(X1, by = "user_id") %>%
  left_join(X2, by = "user_id") 

colnames(main)[2] <- "response"

```





